application: lxbus
version: 1
runtime: python
api_version: 1

inbound_services:
- mail

handlers:
- url: /_ah/mail/carris@lxbus\.appspotmail\.com 
  script: main.py 
  login: admin
- url: /.*
  script: main.py
